"""Voice endpoints -- mic input (speech-to-text) and serving TTS output
generated by api/routes/chat.py back to the browser."""
from __future__ import annotations

from pathlib import Path

from fastapi import APIRouter, File, HTTPException, UploadFile
from fastapi.responses import FileResponse

router = APIRouter(tags=["voice"])


@router.post("/api/voice/transcribe")
async def transcribe_audio(file: UploadFile = File(...)) -> dict[str, str]:
    from ai.speech.stt import transcribe

    audio_bytes = await file.read()
    try:
        text = transcribe(audio_bytes, filename=file.filename, raise_errors=True)
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Transcription failed: {exc}") from exc

    if not text:
        raise HTTPException(status_code=422, detail="Could not transcribe the audio.")

    return {"text": text}


@router.get("/api/audio/{token}")
def get_audio(token: str):
    from api.audio_store import resolve

    path = resolve(token)
    if not path or not Path(path).exists():
        raise HTTPException(status_code=404, detail="Audio not found or expired.")

    suffix = Path(path).suffix.lower()
    media_type = "audio/wav" if suffix == ".wav" else "audio/mpeg"
    return FileResponse(path, media_type=media_type)
